[pytest]
pythonpath = .
testpaths = tests
addopts = -q -p no:pytest_cases
filterwarnings =
	ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx\._client
	ignore:Accessing argon2\.__version__ is deprecated.*:DeprecationWarning:passlib\.handlers\.argon2
	ignore:ARC4 has been moved to cryptography\.hazmat\.decrepit\.ciphers\.algorithms\.ARC4.*:Warning:pypdf\._crypt_providers\._cryptography
