"""replace demo user field with profile prefs

Revision ID: 0384415902c5
Revises: ff05ce8c87e6
Create Date: 2026-04-14 12:23:00.913234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0384415902c5'
down_revision: Union[str, None] = 'ff05ce8c87e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_exam_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(), nullable=True))
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'target_exam_year')
    # ### end Alembic commands ###
