"""add badges and streak activity

Revision ID: 2698add98b67
Revises: 0384415902c5
Create Date: 2026-04-14 13:11:39.847343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2698add98b67'
down_revision: Union[str, None] = '0384415902c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('badges', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'last_activity_date')
    # ### end Alembic commands ###
